language: rust
sudo: true
rust:
  - stable
  - beta
  - nightly
os:
  - linux
matrix:
  allow_failures:
    - rust: nightly
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
script:
  - cargo build -v
  - sudo env "PATH=$PATH" cargo test -j 1 -- --nocapture
  - sudo env "PATH=$PATH" cargo test -j 1 -- --nocapture --ignored
